services:

  resource-service:
    build:
      context: .
      dockerfile: resource-service/Dockerfile
    image: mao-resource-service:latest
    container_name: resource-service
#    ports:
#      - "8081:8081"
    env_file:
      - resource-service.env
    networks:
      - resource-network
      - inter-service-network
    depends_on:
      - postgres-resource
      - song-service
      - service-discovery

  postgres-resource:
    image: postgres:17-alpine
    container_name: postgres-resource
    env_file:
      - postgres-resource-17.env
    volumes:
      - ./resource-service/src/main/resources/db/migration/:/docker-entrypoint-initdb.d
    #    volumes:
    #      - ~/mp3-resource:/var/lib/postgresql/data
#    ports:
#      - "54321:5432"
    networks:
      - resource-network

  song-service:
    build:
      context: .
      dockerfile: song-service/Dockerfile
    image: mao-song-service:latest
    deploy:
      replicas: 2
    env_file:
      - song-service.env
    networks:
      - song-network
      - inter-service-network
    depends_on:
      - postgres-song
      - service-discovery

  postgres-song:
    image: postgres:17-alpine
    container_name: postgres-song
    env_file:
      - postgres-song-17.env
    volumes:
      - ./song-service/src/main/resources/db/migration/:/docker-entrypoint-initdb.d
    #    volumes:
    #      - ~/mp3-song:/var/lib/postgresql/data
#    ports:
#      - "54322:5432"
    networks:
      - song-network

  service-discovery:
    build:
      context: .
      dockerfile: service-discovery/Dockerfile
    image: mao-service-discovery:latest
    container_name: service-discovery
    ports:
      - "8083:8083"
    env_file:
      - service-discovery.env
    networks:
      - inter-service-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: mao-api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - api-gateway.env
    networks:
      - inter-service-network
    depends_on:
      - service-discovery

networks:
  resource-network:
    driver: bridge
  song-network:
    driver: bridge
  inter-service-network:
    driver: bridge