server:
  port: 8082
spring:
  application:
    name: song-service
  devtools:
    livereload:
      port: 45730
  r2dbc:
    url: r2dbc:postgresql://host.docker.internal:54322/postgres
    username: song_user
    password: song_password
  flyway:
    enabled: true
    locations: classpath:db/migration
    user: song_user
    password: song_password
    url: jdbc:postgresql://host.docker.internal:54322/postgres
