server:
  port: 8082
spring:
  application:
    name: song-service
  devtools:
    livereload:
      port: 45730
  r2dbc:
    url: r2dbc:postgresql://postgres-song:54322/songdb
    username: song_user
    password: song_password
  flyway:
    enabled: false
    locations: classpath:db/migration
    user: song_user
    password: song_password
    url: jdbc:postgresql://postgres-song:54322/songdb
