services:

  postgres:
    image: postgres:17
    container_name: postgres-resource
    env_file:
      - postgres-17.env
#    volumes:
#      - ~/mp3-resource:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - mp3-network

networks:
  mp3-network:
    driver: bridge
