server:
  port: 8081
spring:
  application:
    name: resource-service
  devtools:
    livereload:
      port: 45729
  r2dbc:
    url: r2dbc:postgresql://localhost:54321/resourcedb
    username: resource_user
    password: resource_password
  flyway:
    enabled: false
    locations: classpath:db/migration
    user: resource_user
    password: resource_password
    url: jdbc:postgresql://localhost:54321/resourcedb
  codec:
    max-in-memory-size: 50MB

song-service:
  url: http://song-service:8082