server:
  port: 8081
spring:
  application:
    name: resource-service
  devtools:
    livereload:
      port: 45729
  r2dbc:
    url: r2dbc:postgresql://host.docker.internal:54321/postgres
    username: resource_user
    password: resource_password
  flyway:
    enabled: true
    locations: classpath:db/migration
    user: resource_user
    password: resource_password
    url: jdbc:postgresql://host.docker.internal:54321/postgres
  codec:
    max-in-memory-size: 50MB

song-service:
  url: http://host.docker.internal:8082